name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build && pip install pybind11

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_PYTHON_BINDINGS=TRUE -G Ninja

      - name: Build
        run: cmake --build build

      - name: Run Tests
        run: cd build && ctest --output-on-failure
